---
- name: Configure docker 
  hosts: deployserver
  become: true

  tasks:

    - name: Install docker
      apt: 
       name: docker.io
       state: present

    - name: Start the docker service
      become: true
      service:
        name: docker
        state: started

    - name: Run the docker image
      docker_container:
        name: Banking
        image: annapoornakaradi/banking_finance:latest
        state: started
        recreate: yes
        expose:
          - 8081
          - 8080
        ports:
          - "8080:8081"



